version: "3.2"
services:
  laravel-study-test:
    image: pauly/laravel-study-test:latest
    env_file:
      - ./build/env/laravel-study-test.env
    networks:
      - net
    ports:
      - '8080:80'
    volumes:
      - ./dist:/var/www/html:rw
    restart: always

volumes:
  esdata:

networks:
  net:

